/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from "@metaplex-foundation/umi";
import { Serializer, struct, u64 } from "@metaplex-foundation/umi/serializers";
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from "../shared";

// Accounts.
export type ExtendLockInstructionAccounts = {
  user: Signer;
  lockTokenAccount: PublicKey | Pda;
  lock: PublicKey | Pda;
  mint: PublicKey | Pda;
  tokenProgram?: PublicKey | Pda;
  associatedTokenProgram: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
};

// Data.
export type ExtendLockInstructionData = { newUnlockDate: bigint };

export type ExtendLockInstructionDataArgs = { newUnlockDate: number | bigint };

export function getExtendLockInstructionDataSerializer(): Serializer<
  ExtendLockInstructionDataArgs,
  ExtendLockInstructionData
> {
  return struct<ExtendLockInstructionData>([["newUnlockDate", u64()]], {
    description: "ExtendLockInstructionData",
  }) as Serializer<ExtendLockInstructionDataArgs, ExtendLockInstructionData>;
}

// Args.
export type ExtendLockInstructionArgs = ExtendLockInstructionDataArgs;

// Instruction.
export function extendLock(
  context: Pick<Context, "programs">,
  input: ExtendLockInstructionAccounts & ExtendLockInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    "valhalla",
    "D93S1f9iaTDXaLXXeyFVLcXX7wJiCBbk2Jqe1SmbWk2k"
  );

  // Accounts.
  const resolvedAccounts = {
    user: {
      index: 0,
      isWritable: true as boolean,
      value: input.user ?? null,
    },
    lockTokenAccount: {
      index: 1,
      isWritable: true as boolean,
      value: input.lockTokenAccount ?? null,
    },
    lock: {
      index: 2,
      isWritable: true as boolean,
      value: input.lock ?? null,
    },
    mint: {
      index: 3,
      isWritable: false as boolean,
      value: input.mint ?? null,
    },
    tokenProgram: {
      index: 4,
      isWritable: false as boolean,
      value: input.tokenProgram ?? null,
    },
    associatedTokenProgram: {
      index: 5,
      isWritable: false as boolean,
      value: input.associatedTokenProgram ?? null,
    },
    systemProgram: {
      index: 6,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
  } as ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: ExtendLockInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.tokenProgram.value) {
    resolvedAccounts.tokenProgram.value = context.programs.getPublicKey(
      "splToken",
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
    );
    resolvedAccounts.tokenProgram.isWritable = false;
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      "splSystem",
      "11111111111111111111111111111111"
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    "programId",
    programId
  );

  // Data.
  const data = getExtendLockInstructionDataSerializer().serialize(
    resolvedArgs as ExtendLockInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    {
      instruction: { keys, programId, data },
      signers,
      bytesCreatedOnChain,
    },
  ]);
}
