/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from "@metaplex-foundation/umi";
import { Serializer, struct, u64 } from "@metaplex-foundation/umi/serializers";
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from "../shared";

// Accounts.
export type InitInstructionAccounts = {
  admin: Signer;
  locker: PublicKey | Pda;
  treasury: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
};

// Data.
export type InitInstructionData = { fee: bigint };

export type InitInstructionDataArgs = { fee: number | bigint };

export function getInitInstructionDataSerializer(): Serializer<
  InitInstructionDataArgs,
  InitInstructionData
> {
  return struct<InitInstructionData>([["fee", u64()]], {
    description: "InitInstructionData",
  }) as Serializer<InitInstructionDataArgs, InitInstructionData>;
}

// Args.
export type InitInstructionArgs = InitInstructionDataArgs;

// Instruction.
export function init(
  context: Pick<Context, "programs">,
  input: InitInstructionAccounts & InitInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    "valhalla",
    "D93S1f9iaTDXaLXXeyFVLcXX7wJiCBbk2Jqe1SmbWk2k"
  );

  // Accounts.
  const resolvedAccounts = {
    admin: {
      index: 0,
      isWritable: true as boolean,
      value: input.admin ?? null,
    },
    locker: {
      index: 1,
      isWritable: true as boolean,
      value: input.locker ?? null,
    },
    treasury: {
      index: 2,
      isWritable: false as boolean,
      value: input.treasury ?? null,
    },
    systemProgram: {
      index: 3,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
  } as ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: InitInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      "splSystem",
      "11111111111111111111111111111111"
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    "programId",
    programId
  );

  // Data.
  const data = getInitInstructionDataSerializer().serialize(
    resolvedArgs as InitInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    {
      instruction: { keys, programId, data },
      signers,
      bytesCreatedOnChain,
    },
  ]);
}
