[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
valhalla = "GQKWvZqbZrwCsLpsRu1Jov8iKNwvHE4af7aEw7khwhun"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mjm_0x/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
