[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
valhalla = "5PypERESHinFR5gzXQnWnJkC2U4QTQqi34RhmjpvFRkC"

[programs.localnet]
valhalla = "5PypERESHinFR5gzXQnWnJkC2U4QTQqi34RhmjpvFRkC"

[programs.mainnet]
valhalla = "5PypERESHinFR5gzXQnWnJkC2U4QTQqi34RhmjpvFRkC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./.keys/id.json"

[scripts]
create-devnet-data = "yarn run ts-node ./scripts/create-devnet-data.ts"
init-config = "yarn ts-node ./scripts/init.ts"
mint-dev-tokens = "yarn run ts-node ./scripts/mint-dev-tokens.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/valhalla.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
