[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
valhalla = "D93S1f9iaTDXaLXXeyFVLcXX7wJiCBbk2Jqe1SmbWk2k"
[programs.devnet]
valhalla = "D93S1f9iaTDXaLXXeyFVLcXX7wJiCBbk2Jqe1SmbWk2k"
[programs.mainnet]
valhalla = "D93S1f9iaTDXaLXXeyFVLcXX7wJiCBbk2Jqe1SmbWk2k"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./.keys/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/valhalla.ts"
mint-dev-tokens = "yarn run ts-node ./scripts/mint-dev-tokens.ts"
init = "yarn ts-node ./scripts/init.ts"
