/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link Lock}
 * @category Accounts
 * @category generated
 */
export type LockArgs = {
  user: web3.PublicKey
  mint: web3.PublicKey
  lockTokenAccount: web3.PublicKey
  userTokenAccount: web3.PublicKey
  lockedDate: beet.bignum
  unlockDate: beet.bignum
}

export const lockDiscriminator = [8, 255, 36, 202, 210, 22, 57, 137]
/**
 * Holds the data for the {@link Lock} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Lock implements LockArgs {
  private constructor(
    readonly user: web3.PublicKey,
    readonly mint: web3.PublicKey,
    readonly lockTokenAccount: web3.PublicKey,
    readonly userTokenAccount: web3.PublicKey,
    readonly lockedDate: beet.bignum,
    readonly unlockDate: beet.bignum
  ) {}

  /**
   * Creates a {@link Lock} instance from the provided args.
   */
  static fromArgs(args: LockArgs) {
    return new Lock(
      args.user,
      args.mint,
      args.lockTokenAccount,
      args.userTokenAccount,
      args.lockedDate,
      args.unlockDate
    )
  }

  /**
   * Deserializes the {@link Lock} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [Lock, number] {
    return Lock.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Lock} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<Lock> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Lock account at ${address}`)
    }
    return Lock.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'VHDaKPFJHN3c4Vcb1441HotazGQFa4kGoMik9HMRVQh'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, lockBeet)
  }

  /**
   * Deserializes the {@link Lock} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Lock, number] {
    return lockBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Lock} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return lockBeet.serialize({
      accountDiscriminator: lockDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Lock}
   */
  static get byteSize() {
    return lockBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Lock} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Lock.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link Lock} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === Lock.byteSize
  }

  /**
   * Returns a readable version of {@link Lock} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      user: this.user.toBase58(),
      mint: this.mint.toBase58(),
      lockTokenAccount: this.lockTokenAccount.toBase58(),
      userTokenAccount: this.userTokenAccount.toBase58(),
      lockedDate: (() => {
        const x = <{ toNumber: () => number }>this.lockedDate
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      unlockDate: (() => {
        const x = <{ toNumber: () => number }>this.unlockDate
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const lockBeet = new beet.BeetStruct<
  Lock,
  LockArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['user', beetSolana.publicKey],
    ['mint', beetSolana.publicKey],
    ['lockTokenAccount', beetSolana.publicKey],
    ['userTokenAccount', beetSolana.publicKey],
    ['lockedDate', beet.u64],
    ['unlockDate', beet.u64],
  ],
  Lock.fromArgs,
  'Lock'
)
