/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import { VestingType, vestingTypeBeet } from '../types/VestingType'

/**
 * Arguments used to create {@link TokenLock}
 * @category Accounts
 * @category generated
 */
export type TokenLockArgs = {
  creator: web3.PublicKey
  mint: web3.PublicKey
  name: number[] /* size: 32 */
  totalVestingDuration: beet.bignum
  createdTimestamp: beet.bignum
  vestingType: VestingType
}

export const tokenLockDiscriminator = [73, 228, 144, 241, 154, 44, 93, 238]
/**
 * Holds the data for the {@link TokenLock} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class TokenLock implements TokenLockArgs {
  private constructor(
    readonly creator: web3.PublicKey,
    readonly mint: web3.PublicKey,
    readonly name: number[] /* size: 32 */,
    readonly totalVestingDuration: beet.bignum,
    readonly createdTimestamp: beet.bignum,
    readonly vestingType: VestingType
  ) {}

  /**
   * Creates a {@link TokenLock} instance from the provided args.
   */
  static fromArgs(args: TokenLockArgs) {
    return new TokenLock(
      args.creator,
      args.mint,
      args.name,
      args.totalVestingDuration,
      args.createdTimestamp,
      args.vestingType
    )
  }

  /**
   * Deserializes the {@link TokenLock} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [TokenLock, number] {
    return TokenLock.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link TokenLock} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<TokenLock> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find TokenLock account at ${address}`)
    }
    return TokenLock.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '4RjGEao2c8JSNvtbN48PnqzhRHB2iscC9MAN6JXmzypM'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, tokenLockBeet)
  }

  /**
   * Deserializes the {@link TokenLock} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [TokenLock, number] {
    return tokenLockBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link TokenLock} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return tokenLockBeet.serialize({
      accountDiscriminator: tokenLockDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link TokenLock}
   */
  static get byteSize() {
    return tokenLockBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link TokenLock} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      TokenLock.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link TokenLock} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === TokenLock.byteSize
  }

  /**
   * Returns a readable version of {@link TokenLock} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      creator: this.creator.toBase58(),
      mint: this.mint.toBase58(),
      name: this.name,
      totalVestingDuration: (() => {
        const x = <{ toNumber: () => number }>this.totalVestingDuration
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      createdTimestamp: (() => {
        const x = <{ toNumber: () => number }>this.createdTimestamp
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      vestingType: 'VestingType.' + VestingType[this.vestingType],
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const tokenLockBeet = new beet.BeetStruct<
  TokenLock,
  TokenLockArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['creator', beetSolana.publicKey],
    ['mint', beetSolana.publicKey],
    ['name', beet.uniformFixedSizeArray(beet.u8, 32)],
    ['totalVestingDuration', beet.u64],
    ['createdTimestamp', beet.u64],
    ['vestingType', vestingTypeBeet],
  ],
  TokenLock.fromArgs,
  'TokenLock'
)
