/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category Disburse
 * @category generated
 */
export const disburseStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'DisburseInstructionArgs'
)
/**
 * Accounts required by the _disburse_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [] creator
 * @property [] recipient
 * @property [_writable_] devTreasury
 * @property [] config
 * @property [_writable_] vault
 * @property [_writable_] vaultAta
 * @property [_writable_] signerGovernanceAta
 * @property [_writable_] creatorGovernanceAta
 * @property [_writable_] recipientAta
 * @property [] mint
 * @property [_writable_] governanceTokenMint
 * @property [] governanceTokenProgram
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category Disburse
 * @category generated
 */
export type DisburseInstructionAccounts = {
  signer: web3.PublicKey
  creator: web3.PublicKey
  recipient: web3.PublicKey
  devTreasury: web3.PublicKey
  config: web3.PublicKey
  vault: web3.PublicKey
  vaultAta: web3.PublicKey
  signerGovernanceAta: web3.PublicKey
  creatorGovernanceAta: web3.PublicKey
  recipientAta: web3.PublicKey
  mint: web3.PublicKey
  governanceTokenMint: web3.PublicKey
  tokenProgram?: web3.PublicKey
  governanceTokenProgram: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
}

export const disburseInstructionDiscriminator = [
  68, 250, 205, 89, 217, 142, 13, 44,
]

/**
 * Creates a _Disburse_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category Disburse
 * @category generated
 */
export function createDisburseInstruction(
  accounts: DisburseInstructionAccounts,
  programId = new web3.PublicKey('BBczhggWEH5Y5zZNJjgLDWhZhfaSjxm1TcLpYhB79RgY')
) {
  const [data] = disburseStruct.serialize({
    instructionDiscriminator: disburseInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.creator,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.recipient,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.devTreasury,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultAta,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.signerGovernanceAta,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.creatorGovernanceAta,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.recipientAta,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.governanceTokenMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.governanceTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
