[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
valhalla = "CaynZZxoLCM8zJjnrC1KGv3R4X2BCzaSynkVRSJgbLdC"

[programs.localnet]
valhalla = "CaynZZxoLCM8zJjnrC1KGv3R4X2BCzaSynkVRSJgbLdC"

[programs.mainnet]
valhalla = "CaynZZxoLCM8zJjnrC1KGv3R4X2BCzaSynkVRSJgbLdC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./.keys/id.json"

[scripts]
create-data = "yarn run ts-node ./scripts/create-data.ts"
init = "yarn ts-node ./scripts/init.ts"
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
