/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CreateLock
 * @category generated
 */
export type CreateLockInstructionArgs = {
  unlockDate: beet.bignum
  depositAmount: beet.bignum
}
/**
 * @category Instructions
 * @category CreateLock
 * @category generated
 */
export const createLockStruct = new beet.BeetArgsStruct<
  CreateLockInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['unlockDate', beet.u64],
    ['depositAmount', beet.u64],
  ],
  'CreateLockInstructionArgs'
)
/**
 * Accounts required by the _createLock_ instruction
 *
 * @property [_writable_, **signer**] user
 * @property [_writable_] lock
 * @property [_writable_] lockTokenAccount
 * @property [_writable_] userTokenAccount
 * @property [] mint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category CreateLock
 * @category generated
 */
export type CreateLockInstructionAccounts = {
  user: web3.PublicKey
  lock: web3.PublicKey
  lockTokenAccount: web3.PublicKey
  userTokenAccount: web3.PublicKey
  mint: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createLockInstructionDiscriminator = [
  171, 216, 92, 167, 165, 8, 153, 90,
]

/**
 * Creates a _CreateLock_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateLock
 * @category generated
 */
export function createCreateLockInstruction(
  accounts: CreateLockInstructionAccounts,
  args: CreateLockInstructionArgs,
  programId = new web3.PublicKey('VHDaKPFJHN3c4Vcb1441HotazGQFa4kGoMik9HMRVQh')
) {
  const [data] = createLockStruct.serialize({
    instructionDiscriminator: createLockInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.user,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.lock,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lockTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
