/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category DisburseVestingSchedule
 * @category generated
 */
export const disburseVestingScheduleStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'DisburseVestingScheduleInstructionArgs'
)
/**
 * Accounts required by the _disburseVestingSchedule_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [] creator
 * @property [] recipient
 * @property [_writable_] vestingSchedule
 * @property [_writable_] vestingScheduleTokenAccount
 * @property [_writable_] recipientTokenAccount
 * @property [] mint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category DisburseVestingSchedule
 * @category generated
 */
export type DisburseVestingScheduleInstructionAccounts = {
  signer: web3.PublicKey
  creator: web3.PublicKey
  recipient: web3.PublicKey
  vestingSchedule: web3.PublicKey
  vestingScheduleTokenAccount: web3.PublicKey
  recipientTokenAccount: web3.PublicKey
  mint: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
}

export const disburseVestingScheduleInstructionDiscriminator = [
  91, 85, 173, 155, 103, 56, 206, 100,
]

/**
 * Creates a _DisburseVestingSchedule_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category DisburseVestingSchedule
 * @category generated
 */
export function createDisburseVestingScheduleInstruction(
  accounts: DisburseVestingScheduleInstructionAccounts,
  programId = new web3.PublicKey('kY1w5a15ADvW28ZKnoSmbK53LnrBdwiUX5gg4fHq6nc')
) {
  const [data] = disburseVestingScheduleStruct.serialize({
    instructionDiscriminator: disburseVestingScheduleInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.creator,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.recipient,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vestingSchedule,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vestingScheduleTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.recipientTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
