/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as splToken from "@solana/spl-token";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category UpdateScheduledPayment
 * @category generated
 */
export const updateScheduledPaymentStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */;
}>(
  [["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)]],
  "UpdateScheduledPaymentInstructionArgs",
);
/**
 * Accounts required by the _updateScheduledPayment_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] creator
 * @property [_writable_] recipient
 * @property [] newRecipient
 * @property [_writable_] scheduledPayment
 * @property [] mint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category UpdateScheduledPayment
 * @category generated
 */
export type UpdateScheduledPaymentInstructionAccounts = {
  signer: web3.PublicKey;
  creator: web3.PublicKey;
  recipient: web3.PublicKey;
  newRecipient: web3.PublicKey;
  scheduledPayment: web3.PublicKey;
  mint: web3.PublicKey;
  tokenProgram?: web3.PublicKey;
  associatedTokenProgram: web3.PublicKey;
  systemProgram?: web3.PublicKey;
};

export const updateScheduledPaymentInstructionDiscriminator = [
  243, 41, 111, 82, 97, 102, 66, 160,
];

/**
 * Creates a _UpdateScheduledPayment_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category UpdateScheduledPayment
 * @category generated
 */
export function createUpdateScheduledPaymentInstruction(
  accounts: UpdateScheduledPaymentInstructionAccounts,
  programId = new web3.PublicKey(
    "AGRjM1d3GyCGawuEKpQZo68bxkF4QY1nFwo3NUxsMvPN",
  ),
) {
  const [data] = updateScheduledPaymentStruct.serialize({
    instructionDiscriminator: updateScheduledPaymentInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.creator,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.recipient,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.newRecipient,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.scheduledPayment,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
