/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category WithdrawFromLock
 * @category generated
 */
export type WithdrawFromLockInstructionArgs = {
  withdrawAmount: beet.bignum
}
/**
 * @category Instructions
 * @category WithdrawFromLock
 * @category generated
 */
export const withdrawFromLockStruct = new beet.BeetArgsStruct<
  WithdrawFromLockInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['withdrawAmount', beet.u64],
  ],
  'WithdrawFromLockInstructionArgs'
)
/**
 * Accounts required by the _withdrawFromLock_ instruction
 *
 * @property [_writable_, **signer**] user
 * @property [] lock
 * @property [_writable_] lockTokenAccount
 * @property [_writable_] userTokenAccount
 * @property [] mint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category WithdrawFromLock
 * @category generated
 */
export type WithdrawFromLockInstructionAccounts = {
  user: web3.PublicKey
  lock: web3.PublicKey
  lockTokenAccount: web3.PublicKey
  userTokenAccount: web3.PublicKey
  mint: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const withdrawFromLockInstructionDiscriminator = [
  244, 58, 112, 245, 221, 110, 194, 209,
]

/**
 * Creates a _WithdrawFromLock_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category WithdrawFromLock
 * @category generated
 */
export function createWithdrawFromLockInstruction(
  accounts: WithdrawFromLockInstructionAccounts,
  args: WithdrawFromLockInstructionArgs,
  programId = new web3.PublicKey('VHDaKPFJHN3c4Vcb1441HotazGQFa4kGoMik9HMRVQh')
) {
  const [data] = withdrawFromLockStruct.serialize({
    instructionDiscriminator: withdrawFromLockInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.user,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.lock,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.lockTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.userTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
